### ISSUE TITLE
java.lang.IndexOutOfBoundsException: setSpan (6 ... 6) ends beyond length 5

### ISSUE THREAD

**Issue by JosephSanjaya** [konifar/creditcard-input-helper#28]
java.lang.IndexOutOfBoundsException: setSpan (6 ... 6) ends beyond length 5
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1325)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:676)
        at android.text.Selection.setSelection(Selection.java:94)
        at android.text.Selection.setSelection(Selection.java:78)
        at android.text.Selection.setSelection(Selection.java:153)
        at io.konifar.cardinputhelper.CardNumberTextWatcher.adjustCursorPos(CardNumberTextWatcher.kt:105)
        at io.konifar.cardinputhelper.CardNumberTextWatcher.formatText(CardNumberTextWatcher.kt:71)
        at io.konifar.cardinputhelper.CardNumberTextWatcher.afterTextChanged(CardNumberTextWatcher.kt:59)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:10654)
        at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:13521)
        at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1277)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:507)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:37)
        at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:131)
        at android.widget.TextView.doKeyDown(TextView.java:8504)
        at android.widget.TextView.onKeyDown(TextView.java:8261)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2819)
        at android.view.View.dispatchKeyEvent(View.java:14074)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:507)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1847)
        at android.app.Activity.dispatchKeyEvent(Activity.java:4064)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:599)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3056)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:409)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6107)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5972)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5427)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5487)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5446)
2020-09-14 12:00:29.330 13674-13674/com.finansialku.mobile E/AndroidRuntime:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5611)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5454)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5668)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5427)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5487)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5446)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5454)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5427)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8301)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8270)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8231)
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:5182)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:238)
        at android.app.ActivityThread.main(ActivityThread.java:7853)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)

**Comment by JosephSanjaya** [comment]
it also happen to CardMonthYearTextWatcher
java.lang.IndexOutOfBoundsException: setSpan (2 ... 2) ends beyond length 1
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1325)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:676)
        at android.text.Selection.setSelection(Selection.java:94)
        at android.text.Selection.setSelection(Selection.java:78)
        at android.text.Selection.setSelection(Selection.java:153)
        at io.konifar.cardinputhelper.CardMonthYearTextWatcher.afterTextChanged(CardMonthYearTextWatcher.kt:50)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:10654)
        at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:13521)
        at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1277)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:507)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:37)
        at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:131)
        at android.widget.TextView.doKeyDown(TextView.java:8504)
        at android.widget.TextView.onKeyDown(TextView.java:8261)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2819)
        at android.view.View.dispatchKeyEvent(View.java:14074)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1933)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:507)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1847)
        at android.app.Activity.dispatchKeyEvent(Activity.java:4064)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:599)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3056)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:409)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6107)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5972)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5427)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5487)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5446)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5611)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5454)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5668)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5427)
2020-09-14 12:03:13.547 14167-14167/com.finansialku.mobile E/AndroidRuntime:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5487)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5446)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5454)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5427)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8301)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8270)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8231)
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:5182)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:238)
        at android.app.ActivityThread.main(ActivityThread.java:7853)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
